---
title: Bericht von der Humangeographischen Sommerschule „Digitale Geographien“
zeit: 26. September bis 1. Oktober 2021
ort: Institut für Geographie der FAU Erlangen-Nürnberg & Online
image: /bilder/Sommerschule_Dig_Geographie_FAU_ER-N_2021.jpg
tags: Berichte Sommerschule
---

<p>
R&uuml;ckblick: Sommerschule &#8222;Digitale Geographien&ldquo; 2021 &ndash; aus Erlangen</p>

<p>Ende September 2021 hat nach elf Jahren wieder eine &#8222;Humangeographische Sommerschulen&ldquo; in Erlangen stattgefunden: Die Sommerschule &#8222;Digitale Geographien&ldquo; bot f&uuml;r Studierende, Promovierende und junge Postdocs aus der gesamten deutschsprachigen Wissenschaftslandschaft eine Woche lang vertiefte Einblicke in das dynamische Forschungsfeld. Eine engagierte Gruppe von Masterstudierenden der Erlanger Kulturgeographie hatte daf&uuml;r im Rahmen einer &#8222;Forschungswerkstatt&ldquo; in vielen Sitzungen ein Jahr lang gemeinsam mit ihren Dozenten (Finn Dammann MA, Dr. Dominik Kremer sowie den Profs. Walker und Glasze) ein facettenreiches Programm ausgearbeitet. Inhaltlich und organisatorisch wurde die Sommerschule dabei unterst&uuml;tzt von dem DFG Wissenschaftsnetz &#8222;Digitale Geographien&ldquo;, aus dem auch zahlreiche externe Wissensschaftler*innen eigene Workshops beigesteuert haben. Vielfach wurde dabei auf Beitr&auml;ge und Impulse aus dem gerade rechtzeitig zur Sommerschule bei UTB erschienenen neuen Handbuch zu Digitalen Geographien zur&uuml;ckgegriffen. </p>

<p>In sechs halb- bzw. ganzt&auml;gigen Workshops setzten sich die TeilnehmerInnen beispielsweise mit grundlegenden Perspektiven der (Sozial-/Kultur-/Human-) Geographie auf die digitale Transformation auseinander (bspw. neue &#8222;hybride&ldquo; Raumkonzepte, geopolitische und geo&ouml;konomische Spannungsfelder in der Gestaltung der digitalen Transformation, Fragen digitaler Ungleichheiten sowie Politischen &Ouml;kologien der Digitalisierung) und diskutierten an konkreten Beispielen methodologische Herausforderungen einer &Uuml;bersetzung von Geographien ins Digitale. Exemplarische Fallstudien erarbeiteten die Teilnehmer*innen selbst&auml;ndig in Kleingruppen &ndash; wie etwa Fragen nach der r&auml;umlichen Gestaltung der grundlegenden Infrastrukturen des Digitalen am Beispiel des sattelitengest&uuml;tzten Starlink-Systems oder nach den sozialr&auml;umlichen Effekten neuer Plattformunternehmen am Beispiel von AirBNB. Zwei &ouml;ffentliche Keynotes zum Verh&auml;ltnis von &#8222;Critical GIS&ldquo; und Digitaler Geographie von Ryan Burns (Calgary) und zu grundlegenden politisch-&ouml;konomischen Strukturen eines sich herausbildenden &#8222;digitalen Kapitalismus&ldquo; durch Philipp Staab (Berlin) er&ouml;ffneten zus&auml;tzliche Impulse &#8222;von au&szlig;en&ldquo;. </p>

<p>Aufgrund der anhaltenden Pandemie-Situation musste die Sommerschule erstmals online organisiert werden. Obwohl unweigerlich der Charme pers&ouml;nlicher Begegnungen auf den Sommerschulen unter dieser Situation gelitten hat, so zeigen die vielen positiven R&uuml;ckmeldungen, dass auch im Digitalen &auml;u&szlig;erst produktive Diskussionen und Begegnungen erm&ouml;glicht wurden. Dennoch steht zu hoffen, dass der weitere Austausch in den Digitalen Geographien zuk&uuml;nftig auch wieder mit echten Begegnungen m&ouml;glich ist &ndash; bspw. auf dem n&auml;chsten Netzwerktreffen im Dezember (s. https://digitale-geographien.de/). Auch die Reihe der Humangeographischen Sommerschulen plant f&uuml;r den September 2022 die R&uuml;ckkehr zur Pr&auml;senz mit einer Woche rund um Themen geographischer Bildungsarbeit in der N&auml;he von Freiburg/Brsg. (https://humangeographische-sommerschulen.de/). <br />
</p>
